#ifndef _diffusion_services_h_
#define _diffusion_services_h_ 1

#include "service/svc-add-topic.h"
#include "service/svc-authentication-deregister.h"
#include "service/svc-authentication.h"
#include "service/svc-authentication-register.h"
#include "service/svc-change-principal.h"
#include "service/svc-fetch.h"
#include "service/svc-get-session-properties.h"
#include "service/svc-missing-topic.h"
#include "service/svc-msg-receiver-registration.h"
#include "service/svc-notify-subscription.h"
#include "service/svc-notify-unsubscription.h"
#include "service/svc-ping-system.h"
#include "service/svc-ping-user.h"
#include "service/svc-remove-topics.h"
#include "service/svc-security-control.h"
#include "service/svc-send-msg.h"
#include "service/svc-send-msg-to-session.h"
#include "service/svc-send-msg-to-filter.h"
#include "service/svc-send-receiver-client.h"
#include "service/svc-session-properties-event.h"
#include "service/svc-session-properties-event-batch.h"
#include "service/svc-session-properties-registration.h"
#include "service/svc-session-wills.h"
#include "service/svc-subscribe.h"
#include "service/svc-subscription-control.h"
#include "service/svc-system-auth-control.h"
#include "service/svc-topic-control-registration.h"
#include "service/svc-topic-removal.h"
#include "service/svc-unsubscribe.h"
#include "service/svc-update.h"

#endif
