name: chrome-log-beautifier
version: '1.0.0'
summary: An interactive terminal UI for analysing Chrome logs.
description: |
  An interactive terminal UI for analysing Chrome logs.

  Features:
    - Inte
    - Filter by

grade: stable
confinement: strict
base: core18

apps:
  chrome-log-beautifier:
    command: chrome-log-beautifier

parts:

  chrome-log-beautifier:
    plugin: cmake
    build-snaps: [cmake/latest/edge] # We need cmake >= 3.11
    source: https://github.com/ArthurSonzogni/chrome-log-beautifier
    source-type: git
    source-depth: 1
    override-build: |
      /snap/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL \
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

passthrough:
  title: chrome-log-beautifier
  license: MIT
